Emma's todo app
Technigo/project-todos pull request #138
Opened 2020-11-30 18:15 UTC by emma-tech

Link to my deployed project: https://emmas-todolist.netlify.app/

My reflections on how this week's project turned out:
I'm not that happy with the project this time, because I didn't have time for any styling this week 🙈 
.. but anyway, the app is working! And I will continue working on it practicing more Redux and styled components. 

Things I'd like to have clarified or explained in more detail:
I think Redux is really hard to grasp.. Just need some time to recap this project and sprint over Christmas break, then I think things will be more clear 😅

2020-12-01 15:29 UTC, Gabbi-89 requested changes
Emma! You are a pro in writing clean code that is easy to follow with your comments and good structure! ⭐ Your app is also very cute! 🥰 You really need to stop being so hard on yourself. You have reached above the blue level! 💯 And you told me you were not finished?! 
Since I know you have a lot on your work and also have other things going on in your life you need to be more kind to yourself. Try to prioritize and reach the blue level first to avoid stress. And do not forget to ask us, your team members, about help and support! 

You have suceeded with a lot of functions in a structural way and you code is really nice and easy to follow. The app is responsive and you have done a good job using Styled components. 

I put 'Request changes' due to that you easily can fix a more common way in using commas and you can easily add indents were is it missed. I have tried to point out where commas and indents are missing. :) 

Keep up the good work and soon it will feel easier with the Redux! ⭐ ❤️

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/components/TodoList.js
> +        <Header />
I would recommend to import the Header component in App.js instead to make the code more clean since it does not really belong to the TodoList, same for the TodoInput.

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/App.js
> +const store = configureStore({ reducer });
Since I know that you want to have local storage to work, just add this text instead of what you now have on row 11 & 12;
```
// Retrieves the localStorage and use it as the initial state
const persistedStateJSON = localStorage.getItem('task-list');
let persistedState = {};

if (persistedStateJSON) {
  persistedState = JSON.parse(persistedStateJSON);
}

// Creates the store using initital state
const store = createStore(
  reducer, 
  persistedState, 
  window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
);

// Stores the state in localStorage on any change in the redux state 
store.subscribe(() => {
  localStorage.setItem('task-list', JSON.stringify(store.getState()));
});
```

I did also try to comment what the code rows actually does.

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/components/ClearButton.js
> +            <ClearAllButton onClick={clearAllTodos} role="img" aria-label="paper bin">Clear All 🗑</ClearAllButton>
I think there is a recommendation to add emojis in a span element, like the bin here and add the role och aria-label inside the span instead...

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/components/TodoInput.js
> +        </FormContainer>
Nice and clean code 💯

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/components/TodoInput.js
> +    }
I see that you use commas, try to use it everywhere then, as in the end of the curly bracket on row 47 and 48

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/reducers/todos.js
> +        },
I am not fully sure, but I think row 30-32 are possible to make to one line, as below:  
```
removeTodo: (state, action) => {
      state.list.items = state.list.items.filter((item, index) => index !== action.payload)
    },
```

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/reducers/todos.js
> +            state.list.items[itemIndex].isComplete = isComplete;
Very smart of you to use item index as id for the tasks and that it works 😃 🥇

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/reducers/todos.js
> +
Remove this enter space ?

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/index.css
> +}
Think about how this part can be done with styled components instead as the rest of the styling. :) Let me know if you want help to think about it. :)

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/components/TodoItem.js
> +cursor: pointer;
Indents missing!

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/components/TodoInput.js
> +cursor: pointer;
Indents missing

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/components/Header.js
> +}
Commas missing

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/components/ClearButton.js
> +margin: 10px;
Indents missing

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/components/ClearButton.js
> +width: 80%;
Indents missing

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/components/ClearButton.js
> +}
Commas missing

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/components/TodoItem.js
> +    }
Commas missing

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/components/TodoItem.js
> +    }
Commas missing

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/components/TodoItem.js
> +};
Clean and good structure 💯

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/components/TodoList.js
> +text-align: left;
Indents missing

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/components/TodoList.js
> +  `;
One indent to much on line 37

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/components/TodoList.js
> +                itemIndex={index}
Indents missing

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/components/TodoList.js
> +        <Header />
Indents for the content in <BackgroundContainer></BackgroundContainer> are missing

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/components/TodoSummary.js
> +font-weight: bold;
Indents missing

2020-12-01 15:29 UTC, Gabbi-89 commented on code/src/components/TodoSummary.js
> +}
Commas missing

2020-12-13 12:11 UTC, Gabbi-89 approved these changes
Good work Emma with the changes 🌟

2020-12-21 14:30 UTC, HIPPIEKICK commented on code/src/components/ClearButton.js
> +`;
Try to be consistent with indentation - here you have one space and on the other places you have four spaces

2020-12-21 14:32 UTC, HIPPIEKICK commented on code/src/components/TodoInput.js
> +            />
Remember to prevent the user from submitting empty todos :)

2020-12-21 14:33 UTC, HIPPIEKICK commented on code/src/components/TodoItem.js
> +            <DeleteButton onClick={handleDelete}> Delete </DeleteButton>
Maybe this button should not have line-through

2020-12-21 14:34 UTC, HIPPIEKICK commented on code/src/components/TodoInput.js
> +            />
Fix this and you're good to go ⭐

2021-03-09 12:53 UTC, closed without merging