Todo
Technigo/project-todos pull request #158
Opened 2021-04-23 16:17 UTC by matildasvensson85

Link to my deployed project: https://reverent-murdock-6eb4c8.netlify.app/

My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:

2021-04-27 14:26 UTC, leelalaim commented on code/src/components/CompletedTasks.js
> +`
Nice that you have used styled components!

2021-04-27 14:27 UTC, leelalaim commented on code/src/components/Header.js
> +                {/* <DateTitle>Date</DateTitle> */}
Remove the comments from the code :)

2021-04-27 14:28 UTC, leelalaim commented on code/src/reducers/tasks.js
> +    // { id: 4, taskText: 'Homework', isDone: true },
Remove the comments from the code :)

2021-04-27 14:28 UTC, leelalaim commented on code/src/reducers/tasks.js
> +            // store.taskList.push(action.payload)
Remove the comments :)

2021-04-27 14:29 UTC, leelalaim approved these changes
Nice and neat code. Remove the comments that are not needed from the code. The live preview link was not working, check netlify.

2021-05-02 16:23 UTC, KarolCislowski requested changes
please check your link to the netlify because it returns "page not found"

2021-06-12 12:23 UTC, KarolCislowski approved these changes
Good job 👍🏻

2021-11-01 15:04 UTC, closed without merging