Project Todo - Julia Ros
Technigo/project-todos pull request #168
Opened 2021-04-24 19:54 UTC by julialeonieros

Link to my deployed project:
https://zealous-ardinghelli-8278dd.netlify.app/

My reflections on how this week's project turned out:
I'm pretty happy with how the app turned out. It looks best on mobile though. 

Things I'd like to have clarified or explained in more detail:
I have problems getting eslint to work (disabled it before and now it doesn't "work"), so there might be some errors/warnings regarding the formatting that I don't see.

2021-04-27 20:10 UTC, Aepera approved these changes
First impression: I really like the design! Very clean and neat looking, nice colors and color markings. ALso big plus for the coffee animation when all tasks are done! 
Everything is working as supposed to on the app and the responsiveness looks good. The code is clean and easy to read.

2021-04-27 20:10 UTC, Aepera commented on code/src/components/AddTodo.js
> +`
Nice job with using styled components throughout the project 👌

2021-04-27 20:10 UTC, Aepera commented on code/src/components/AddTodo.js
> +          <i className="fas fa-plus"></i>
I like the font awesome details

2021-04-27 20:10 UTC, Aepera commented on code/src/components/TodoList.js
> +        <EmptyTodoList />
Great use of a ternary operator to display the Empty list component!

2021-04-27 20:10 UTC, Aepera commented on code/src/reducers/todos.js
> +      const checkedTasks = store.tasks.map((todo) => {
Well done with immutable approach 👍

2021-05-01 21:46 UTC, KarolCislowski requested changes
Great app with a nice and clean interface. Please fix the issue with not needed scroll bars 😸

2021-05-01 21:46 UTC, KarolCislowski commented on code/src/components/Todo.js
> +  overflow: scroll;
I think `overflow: auto;` would do a trick 
![image](https://user-images.githubusercontent.com/50926159/116795699-35121480-aad7-11eb-8019-75dd243a4f04.png)

2021-06-12 12:27 UTC, KarolCislowski approved these changes
Great work!

2021-11-01 15:04 UTC, closed without merging