Project Todo Fethullah
Technigo/project-todos pull request #173
Opened 2021-04-25 11:11 UTC by FD000

Link to my deployed project:

My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:

2021-04-28 20:33 UTC, Martno96 requested changes
Your code looks clean! Easy to read apart from some line break needed here and there (see comments). I unfortunately couldn't find a build link anywhere, so I'm yet to test how it runs and feels. Hit me up with it later and I'll take a look :) I'll be marking this as requesting changes, since I think a build link is required

2021-04-28 20:33 UTC, Martno96 commented on Installments.md
> +5) npm install @material-ui/icons
This is super handy!

2021-04-28 20:33 UTC, Martno96 commented on code/src/components/EmptyPage.js
> +            It seems like you don't have any Todos at the moment. Take your time and enjoy the moment &#128513;
Love this! :D

2021-04-28 20:33 UTC, Martno96 commented on code/src/components/TodoForm.js
> +            alert("You can't leave the input field empty!")
I like the phrasing! :)

2021-04-28 20:33 UTC, Martno96 commented on code/src/components/TodoForm.js
> +                fromNow: moment().add(3, 'days').calendar(),
Would be nice if this was customizable in a future build :)

2021-04-28 20:33 UTC, Martno96 commented on code/src/components/TodoForm.js
> +                    label="+ Add Todo"
An alternative would be to use the material ui AddIcon instead of the "+" character

2021-04-28 20:33 UTC, Martno96 commented on code/src/components/TodoList.js
> +            {(items.length === 0) ? <EmptyPage /> :
ternary operators ftw! :D

2021-04-28 20:33 UTC, Martno96 commented on code/src/components/TodoList.js
> +                                {(moment().calendar() === todo.fromNow) ? <p className="deadline-passed"> Created: {moment(todo.date).format('Do MMMM YYYY')}</p> : <p className="within-deadline"> Cre
this ternary operator does get very long. Consider line-breaking it, maybe like this:
```suggestion
`{(moment().calendar() === todo.fromNow) 
    ? <p className="deadline-passed">
        Created: {moment(todo.date).format('Do MMMM YYYY')}
    </p>
    : <p className="within-deadline">
        Created: {moment(todo.date).format('Do MMMM YYYY')}
    </p>}`
```

2021-04-28 20:33 UTC, Martno96 commented on code/src/components/TodoList.js
> +                                        label={todo.isComplete ? <p className="completed-task">Completed</p> : <p className="not-completed-task">Mark as Completed</p>}
use the rule of line-breaking when you got more than two JSX attributes, even for nested attributes
```suggestion
control={
    <Checkbox 
        checked={todo.isComplete}
        onChange={() => dispatch(todos.actions.toggleComplete(todo.id))}
    />}
label={
    todo.isComplete 
        ? <p className="completed-task">
            Completed
        </p> 
        : <p className="not-completed-task">
            Mark as Completed
        </p>}
```

2021-04-28 20:33 UTC, Martno96 commented on code/src/components/TopSection.js
> +    const amountOfNotCompleted = isCompleted.filter(x =>  x.isComplete === false).length;
I appreciate the commitment to semantic naming, even in the face of long variable names :D improves readability

2021-04-28 20:33 UTC, Martno96 commented on code/src/components/TopSection.js
> +            :
Now that's good line-breaking for ternary operators! :D

2021-04-28 20:33 UTC, Martno96 commented on code/src/components/TopSection.js
> +                        {(summary === 0) ? "" : <Button variant="contained" color="secondary" startIcon={<DeleteIcon />} onClick={() => dispatch(todos.actions.clearAll())}>Delete all</Button>}
just do as you did above and you golden 👌

2021-05-01 21:01 UTC, KarolCislowski requested changes
Please add the Netlify link 😸

2021-06-08 06:18 UTC, KarolCislowski approved these changes
💯

2021-06-08 06:18 UTC, KarolCislowski commented on code/src/components/TodoForm.js
> +                    onClick={onFormSubmit}
because your button has no type of `submit` then when you use enter to submit data, your page reloads and all your state is gone 😭

2021-06-08 06:18 UTC, KarolCislowski commented on code/src/reducers/todos.js
> +        items: []
nice initial state

2021-11-01 15:04 UTC, closed without merging