Project-todos
Technigo/project-todos pull request #185
Opened 2021-04-25 16:58 UTC by tuttibalutti

Link to my deployed project: https://cocky-galileo-15b920.netlify.app/ 

My reflections on how this week's project turned out: I wish I had more time to work with the todo app and really explore the Redux functionality instead of feeling like I was just "copying" the lectures. But one thing I'm proud of is that I managed to use the store.subscribe() to add items to the local storage.    

Things I'd like to have clarified or explained in more detail: Everything🙃

2021-04-28 19:01 UTC, klimenko3007 requested changes
Congrats, Emma! I alway admire how much you manage to do given you are working 100%!!! Impressive! Good structure of components, nice and clean App.js, and great that you managed to get the subscribe function working!
I request changes to fix the indentation to make it consistent throughout the project and in accordance with the Technigo guidelines. 
Great job!!!

2021-04-28 19:01 UTC, klimenko3007 commented on code/src/App.js
> +})
Really impressing that you have created the local storage to keep track of todos! Congrats!!1

2021-04-28 19:01 UTC, klimenko3007 commented on code/src/App.js
> +    </Provider>
Nice and clean structure in the App.js!

2021-04-28 19:01 UTC, klimenko3007 commented on code/src/components/Header.js
> +	const completedItems = items.filter(item => item.isComplete)
It could just be how it is reflected in GitHub, but I think it is indented too much here

2021-04-28 19:01 UTC, klimenko3007 commented on code/src/components/Header.js
> +  )
Indentation here does not seem correct

2021-04-28 19:01 UTC, klimenko3007 commented on code/src/components/TodoForm.js
> +import React, { useState } from 'react'
For this component, I think the indentation is 4 spaces and in our guidelines it should be 2

2021-04-28 19:01 UTC, klimenko3007 commented on code/src/components/TodoList.js
> +	const dispatch = useDispatch()
Only one indentation issue line 9

2021-04-28 19:01 UTC, klimenko3007 commented on code/src/reducers/todos.js
> +import { createSlice } from '@reduxjs/toolkit'
I think you should reset the default setting for your indentation in the VS Code to be 2 spaces instead of 4. It looks a bit neater with consistent indentation in all files. At the moment it is not consistent.

2021-05-01 19:30 UTC, KarolCislowski commented on code/src/reducers/todos.js
> +import { createSlice } from '@reduxjs/toolkit'
for sure. check your prettier's configurations.

2021-05-01 19:32 UTC, KarolCislowski approved these changes
Great App! Nice work with local storage. 

Please check your Prettier to fix the indentation issue 😸

2021-11-01 15:04 UTC, closed without merging