project todo - Noemi
Technigo/project-todos pull request #190
Opened 2021-04-25 20:05 UTC by NoemiSalome

Link to my deployed project: [https://project-todo-noemi.netlify.app/]

My reflections on how this week's project turned out: a lot of information and still trying to put everything into its place. discovered styling with styled components, which is great fun! would have loved to implement a button to delete all tasks, but couldn't make it work. Looking forward to some more redux :)

Things I'd like to have clarified or explained in more detail:
styling: somehow when submiting a task the container shrinks and the tasks don't take the width of the whole container. I tried putting width = 100%, but didn't work. Would love some input on that. spent hours trying to solve it. THANKS 😊

2021-04-28 22:46 UTC, MarySparrow requested changes
Awesome job Noemi, I always enjoy your projects, I still cant believe you succeed to hand them in in time and completed when starting sometimes very late in the week. You have some major skills and high stress level girl! 💃  and on top of that always have time for a break and talk about my CSS issues 😂

I hope I get to work with you on another project , that would be truly fun! 👯 

✔️Just fix that little delete button and you are minutes from another completed project ✔️

2021-04-28 22:46 UTC, MarySparrow commented on README.md
>  ## View it live
It's a great way to start your project sketching it first, and it turned out very nice and pretty! Be proud! I would love to see that video on how to do the Lottie adding, way to go to get that setup! 😍🤩 
Some Lottie envy going on over here 🤠🤠

2021-04-28 22:46 UTC, MarySparrow commented on code/src/reducers/tasks.js
> +        },
There is a little issue with the deleting of a task, it removes the first item of the list not the one you click. This has to do with a mutable approach vs immutability. I cannot say why it is not working but I can show you how the immutability approach can be written and you can try that instead. Maybe you need to write in more than one place, a little help for that please code coach 💁 

```
removeTasTk: (store, action) => {
      const removeTask = store.tasks.filter(todo => todo.id !== action.payload) 
        store.tasks = removeTask
    }
```

2021-04-28 22:46 UTC, MarySparrow commented on code/src/components/Header.js
> +                </Normaltext>
Good job in getting the time , cred for the extra effort! --> a little note though, for future projects (or whenever we have the time to go back to fix all our piling up stuff) , moment is no longer being maintained and so there is a high risk of bugs and so on.. 🐞 🐞

2021-04-28 22:46 UTC, MarySparrow commented on code/src/components/TaskList.js
> +
A wrote the longest word ever and it worked like a charm, must be this setting you remembered right here 👍

2021-04-28 22:46 UTC, MarySparrow commented on code/src/components/TaskList.js
> +
I know you said you were gonna work with styled component for the first time (i think) this week and it turned out great! ⭐  I also prefer that now, lets find out the advanced stuff too, React for life haha! 😊😊

2021-04-28 22:46 UTC, MarySparrow commented on code/src/components/TaskList.js
> +                    ))}
very clear namings ! 👌

2021-04-28 22:46 UTC, MarySparrow commented on code/src/components/TaskList.js
> +`
Maybe add a max-width here, the textinput field get a bit large on the laptop 💻 (and I know I messed your styling in the last minute yesterday haha, sooorrryyy!) 🙇‍♀️

2021-04-28 22:46 UTC, MarySparrow commented on code/src/App.js
> +`
You always remember those media Qs 😺😺 good job!

2021-04-28 22:46 UTC, MarySparrow commented on code/src/components/Header.js
> +    const items = useSelector((store) => store.tasks.items)
try to keep the same pattern of space between styled components 👽

2021-05-01 15:12 UTC, KarolCislowski requested changes
Nice work but you need to fix the `remove task` issue to meet blue level requirments. 

Your tasks are taking 100% of container width, so I don't know why they work differently on your machine. 
![image](https://user-images.githubusercontent.com/50926159/116786644-19d7e280-aaa0-11eb-8b07-c96c97262608.png)

2021-05-01 15:12 UTC, KarolCislowski commented on code/src/reducers/tasks.js
> +        },
Yes @MarySparrow is 100% right 🥇

2021-05-31 05:39 UTC, KarolCislowski approved these changes
Great work!

2021-11-01 15:04 UTC, closed without merging