Project 15 - Caroline Fahlgren
Technigo/project-todos pull request #195
Opened 2021-04-25 21:26 UTC by CarolineF3

Link to my deployed project: https://todo-carolinef.netlify.app/

2021-04-28 20:10 UTC, Andrealarsson approved these changes
Great work on this project! 💯 Your todo app looks very cute and clean. The code is easy to read and understand. You are awesome Caroline! 🤩 🙌

2021-04-28 20:10 UTC, Andrealarsson commented on code/src/components/ToDoList.js
> +          ></img>
I can't see your wastebin on the webpage to remove each item? 🤔

2021-04-28 20:10 UTC, Andrealarsson commented on code/src/App.js
> +        />
Really cute image 💮

2021-04-28 20:10 UTC, Andrealarsson commented on code/src/components/Header.js
> +          })}
This is a great solution to show the date 👍

2021-05-01 13:07 UTC, KarolCislowski requested changes
It is a very stylish app, I love the flower details and the font face. 
You need to add the button to remove a single task from the list to meet the requirements 😃

2021-05-01 13:07 UTC, KarolCislowski commented on code/src/components/ToDoList.js
> +          ></img>
Yes this is the only thing that is missing to fulfill the blue requirements 😭

2021-06-12 12:26 UTC, KarolCislowski approved these changes
Great App!

2021-11-01 15:04 UTC, closed without merging