components combined
Technigo/project-todos pull request #196
Opened 2021-04-25 21:30 UTC by nazi-pira

Link to my deployed project:

My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:

2021-04-29 11:17 UTC, Sartish approved these changes
Hi Nazanin! 
I am so impressed with your code! it was so easy to understand it, it is structured and clean🧹. I liked that you divided all the features in smaller components. Very impressive. Also, you used styled-components🙌 ⭐️ I will put the project as approved and the comments are only about commented code that can be removed 😄 But I could not see any link to your deployed project? Would be great if you put this in your readme file! I am also curious to see how it looks deployed 😍

2021-04-29 11:17 UTC, Sartish commented on code/src/Components/CheckBox.js
> +      <span className="checkmark" role="checkbox" aria-checked="false" tabIndex="0"></span>
Nice solution with handling the checkboxes to be complete⭐️

2021-04-29 11:17 UTC, Sartish commented on code/src/Components/ClearButton.js
> +        showDialog={allDialogs.dialog2}
I like that you added a Dialog that pops! The code looks clean and it is easy to understand it!

2021-04-29 11:17 UTC, Sartish commented on code/src/Components/Dialog.js
> +  z-index: 1;
Love that you are using styled components! that box shadow is🙌

2021-04-29 11:17 UTC, Sartish commented on code/src/Components/Dialog.js
> +    }
very nice feature⭐️

2021-04-29 11:17 UTC, Sartish commented on code/src/Components/RemoveButton.js
> +    // dispatch(tasks.actions.removeTask(id))
don't forget to remove commeented out code ☺️

2021-04-29 11:17 UTC, Sartish commented on code/src/Components/header.css
> +  /* border-bottom: solid #ffb677; */
same here, out-commented code can be removed ☺️

2021-04-29 11:17 UTC, Sartish commented on code/src/Components/removebuttons.css
> +  /* background-color: #ff8364; */
here again to be removed 😄

2021-04-29 11:17 UTC, Sartish commented on code/src/reducers/tasks.js
> +  // { id: 5, text: 'Create a todo app', complete: false },
maybe can be deleted also ? If not used for reference of course 😀

2021-05-01 12:53 UTC, KarolCislowski requested changes
Please provide the netlify link

2021-06-12 12:22 UTC, KarolCislowski requested changes

2021-06-12 12:22 UTC, KarolCislowski commented on README.md
I still can't see a link to the hosted version here 😭

2021-07-02 14:17 UTC, closed without merging