Project Todo - Sandra Wallén
Technigo/project-todos pull request #199
Opened 2021-04-25 22:12 UTC by sandra-wallen

**Link to my deployed project:**
https://sandras-todos.netlify.app

**My reflections on how this week's project turned out:**
I'm overall very pleased with how the project turned out. I set up a "data base" with a REST API and put a lot of time on this. The app sends GET, POST, DELETE and PUT requests to the REST API. The PUT request is sent when an item is toggled complete or the item text is updated.

When there are no todos to be displayed an empty state component is mounted and x/x tasks + the check all/uncheck all button component is only mounted when there are items in the data base.

I had many ideas for this project but I didn't have the time to implement them all. See the readme file for a further explanations about me project and the things I would want to implement/fix next

**Things I'd like to have clarified or explained in more detail:**
Since it's always some response time for the API I have also implemented local updates to the store that will show until the response. There's still some glitches in this functionality however, sometimes when an item is deleted the local state updates and filters out that item but then the refetch is executed too quickly, resulting in the deleted item still being in the response and now showing in the list again. I set a setTimeout on the refetches but that didn't do the trick, I will have to investigate this further. Another thing that you should have in mind when using my application is that the restdb didn't provide any documentation on how to do a batch request, or if it's even possible. Therefor the checkAll and uncheckAll functions are just updating locally and will not send any requests to the API.

I have not made the local state update while waiting for the response from the POST request because I didn't know how to think when sending this to the intialState locally, in the object there is an idgenerator and a moment function and if I would just recreate this when updating the state locally it would not generate the same values as the real request sent to the API.

Also, I struggled alot with styling the datepicker initially, and after a while a found that I could overwrite the provided stylesheet for the component but I didn't know how to do this as a styled component, the datepicker is the only element that is styled with vanilla css.

2021-04-28 19:51 UTC, annalenksjo approved these changes
Awesome project, nice design! It was cool that you really pushed the limits and I know you put in a lot more than half-time. The readme was extensive (good job) and it was interesting to follow your process and struggles. 

As you mention there are some remaining bugs. So I guess its kind of a still ongoing project :)

You really did a good job in dividing into (many) components as well. Well structured, good naming. 

Maybe add some other styling to the tasks that are checked, to more easily distinguish them from the ones that are left to do. Also, it would be smooth to add a task with the enter-key as well! 

But all in all great job, a high ambition I applaud you for that!

2021-04-28 19:51 UTC, annalenksjo commented on code/src/components/CheckAllBtn.js
> +        {store.allChecked ? "UNCHECK ALL" : "CHECK ALL"}
Nice implementation with the change of button text!

2021-04-28 19:51 UTC, annalenksjo commented on code/src/components/Header.js
> +`
Is this intentionally blank to create a semantic tag?

2021-04-28 19:51 UTC, annalenksjo commented on code/src/components/Header.js
> +  const weekday = moment().format('dddd')
Nice that you did the moments to constants, makes it easier to follow!

2021-04-28 19:51 UTC, annalenksjo commented on code/src/components/TodoItem.js
> +  const taskDueDate = moment(dueDate).format('MMM Do')
👍

2021-04-28 19:51 UTC, annalenksjo commented on code/src/components/TodoList.js
> +        <EmptyState />
Nice! I liked your empty state pic too!

2021-04-28 19:51 UTC, annalenksjo commented on code/src/index.css
> +.bx--date-picker.bx--date-picker--single .bx--date-picker__input {
wow complicated classnames :P

2021-05-01 12:20 UTC, KarolCislowski requested changes
Please check your netlify link because it is returning 404 Error 😭

2021-05-25 08:05 UTC, KarolCislowski approved these changes
Great APP! I can see you mastered the process of building good, reusable components, which makes your code super clean and easy to maintain 🦸🏻‍♀️

2021-05-25 08:05 UTC, KarolCislowski commented on code/src/components/CustomCheckbox.js
> +`
Impressive 😮

2021-05-25 08:05 UTC, KarolCislowski commented on code/src/components/CustomDatePicker.js
> +      </DatePicker>
Really nice 🥇

2021-05-25 08:05 UTC, KarolCislowski commented on code/src/reducers/tasks.js
> +    },
😮

2021-11-01 15:04 UTC, closed without merging