Project Todo Anna Takman
Technigo/project-todos pull request #50
Opened 2020-04-22 15:56 UTC by annatakman

Link to my deployed project: https://annas-todo-app.netlify.app/

My reflections on how this week's project turned out: A bit easier with Redux this week, but still hard to grasp everything!

2020-04-29 13:17 UTC, HIPPIEKICK requested changes
Good job Anna! It's nice that you can store the todos and that you're continuing with styled components 💅I've made some comments that are suggestions/improvement and most of your code looks good. But, quite a lot of your styled components has messed up indentation, so please go through all of your code (I didn't write comments everywhere) and format it according to guidelines, and I'll approve this! Apart from that - keep it up! ⭐

2020-04-29 13:17 UTC, HIPPIEKICK commented on code/src/App.js
>      </div>
Since you're only returning a single element you can remove the div (if you're not styling it somewhere), and just return the `<Home />` component.

2020-04-29 13:17 UTC, HIPPIEKICK commented on code/src/pages/Home.js
> +})
Nice that you're storing the todos! ⭐

2020-04-29 13:17 UTC, HIPPIEKICK commented on code/src/pages/Home.js
> +        <TodoList></TodoList>
Since this component doesn't have any children, you can just make it self closing:
`<TodoList />`

2020-04-29 13:17 UTC, HIPPIEKICK commented on code/src/components/TodoList.js
> +font-family: 'Work Sans', sans-serif;
Indentation :)

2020-04-29 13:17 UTC, HIPPIEKICK commented on code/src/components/TodoList.js
> +padding: 4% 8%;
Indentation :)

2020-04-29 13:17 UTC, HIPPIEKICK commented on code/src/components/TodoList.js
> +  const list = useSelector(store => store.todos.list)
Since your only using the items-array, it's better to just get that information from the store:
`const items = useSelector(store => store.todos.list.items)`

2020-04-29 13:17 UTC, HIPPIEKICK commented on code/src/components/TodoSummary.js
> +  const list = useSelector(store => store.todos.list)
Same here, if you only need the items-array, get only that:
`const items = useSelector(store => store.todos.list.items)`

2020-04-29 13:17 UTC, HIPPIEKICK commented on code/src/components/TodoInput.js
> +    ></input>
Since input doesn't have any child elements, you can make it self closing:
```
<input
  type="text"
  value={inputValue}
  onChange={event => setInputValue(event.target.value)}
/>
```

2020-04-29 13:17 UTC, HIPPIEKICK commented on code/src/components/TodoInput.js
> +  }
Right now you can save an empty todo. Maybe check if the input is empty or not before dispatching the action or add `required` to the input-field to prevent this.

2020-04-29 13:17 UTC, HIPPIEKICK commented on code/src/components/TodoInput.js
> +  }
I think these would be easier to read and to reuse if they were "their own" styled components:
```
const Input = styled.input`
/*Styling*/
`
```

2020-04-29 13:17 UTC, HIPPIEKICK commented on code/src/components/TodoList.js
> +        {list.items.map((item, index) => (<TodoItem itemIndex={index}></TodoItem>))}
This doesn't have any children either, so you can make it self closing. And don't forget to add a key when you're mapping:
`<TodoItem key={index} item={item} itemIndex={index} />`

2020-04-29 13:17 UTC, HIPPIEKICK commented on code/src/components/ClearButton.js
> +}
Nice with a remove-all-button!

2020-04-29 13:17 UTC, HIPPIEKICK commented on code/src/components/TodoItem.js
> +  }
It would be better to use a unique id instead of the index to deal with the done state. There's an issue now that happens if you write some todos, check the first one and then remove it, the second one will "jump up" to index 0 and become checked.

2020-04-29 13:17 UTC, HIPPIEKICK commented on code/src/reducers/todos.js
> +    },
Add a unique id to your todos that you can use instead of the index, eg. a timestamp.

2020-04-29 13:17 UTC, HIPPIEKICK commented on code/src/reducers/todos.js
> +    },
⭐

2020-04-29 13:17 UTC, HIPPIEKICK commented on code/src/components/TodoItem.js
> +`
Indentation

2020-04-29 18:45 UTC, annatakman commented
I have fixed everything except the bug, I booked a 1:1 on Monday to get help with that. When can the assignment be approved? After the bug is fixed?

2020-04-30 07:57 UTC, HIPPIEKICK approved these changes
Awesome! Indentation looks good, I'm approving this now. No stress about the bug, that was more a suggestion of improvement.

2020-11-09 17:00 UTC, closed without merging