Project 15, Ingrid H
Technigo/project-todos pull request #57
Opened 2020-04-24 08:21 UTC by ingrid2019-ism

Link to my deployed project: I had big troubles with the deployment on Netlify. Tried to follow the Netlify deploy log but couldn´t get it to work...

My reflections on how this week's project turned out: I liked the project! Wish I had more time to add some extra features like local storage.

Things I'd like to have clarified or explained in more detail:

2020-05-05 13:19 UTC, HIPPIEKICK requested changes
Good job Ingrid! It's nice to see that you're adding some extra features like date and clear-button. Please have another look at the code guidelines: [https://www.notion.so/technigo/Guidelines-for-how-to-write-good-code-69ffb59eac4e4358a7c5752efb873c4e](https://www.notion.so/technigo/Guidelines-for-how-to-write-good-code-69ffb59eac4e4358a7c5752efb873c4e) and make sure you're using semantic HTML as much as possible (I made a comment about an input which is a button). I've also made a few comments about indentation. I will approve this as soon as you fix indentation and change the button to be a button - apart from that - well done!

2020-05-05 13:19 UTC, HIPPIEKICK commented on code/src/App.js
>      </div>
Since you're only returning one component here, you don't need to wrap it in a div.

2020-05-05 13:19 UTC, HIPPIEKICK commented on code/src/components/ShowDate.js
> +    </>
Same here, you shouldn't need the fragment since you're only returning one element.

2020-05-05 13:19 UTC, HIPPIEKICK commented on code/src/components/ShowDate.js
> +  const today = d.toDateString()
Nice with a date!

2020-05-05 13:19 UTC, HIPPIEKICK commented on code/src/components/TodoSummery.js
> +  const list = useSelector(store => store.todos.list)
Since you're only using the items-array, it's better to get only that:
`const items = useSelector(store => store.todos.list.items)`

2020-05-05 13:19 UTC, HIPPIEKICK commented on code/src/components/TodoInput.js
> +import { useState } from "react"
You can import these on the same row, since they have the same source:
`import React, { useState } from 'react'`

2020-05-05 13:19 UTC, HIPPIEKICK commented on code/src/components/TodoInput.js
> +    setInputValue('')
Good that you're clearing the input! Right now you can submit empty todos, so maybe set the input-field to be `required`, or check if the input is empty before actually dispatching.

2020-05-05 13:19 UTC, HIPPIEKICK commented on code/src/components/TodoInput.js
> +      ></input>
Don't forget to use semantic HTML - this is a button so why not call it a button? 😉

2020-05-05 13:19 UTC, HIPPIEKICK commented on code/src/components/TodoInput.js
> +      ></input>
Since the input-element doesn't have any children you can just make it self closing instead of with opening and closing tags:
```
<input
  type='text'
  placeholder='Add Todo'
  onChange={event => setInputValue(event.target.value)}
  value={inputValue}
  className='todo-input-text'
/>
```

2020-05-05 13:19 UTC, HIPPIEKICK commented on code/src/components/RemoveAll.js
> +    </button>
Nice with a clear-button!

2020-05-05 13:19 UTC, HIPPIEKICK commented on code/src/components/TodoList.js
> +import { TodoSummery } from 'components/TodoSummery'
Remove unused code

2020-05-05 13:19 UTC, HIPPIEKICK commented on code/src/components/TodoList.js
> +  const list = useSelector(store => store.todos.list)
Same here, you're only using the items-array so get only that instead:
`const items = useSelector(store => store.todos.list.items)`

2020-05-05 13:19 UTC, HIPPIEKICK commented on code/src/components/TodoItem.js
> +  </div >
Nice with conditional styling! Try to be consistent with parentheses after return and maybe clean this up a bit (so the `<div>` gets its own line and the `</div>` don't have a space):
```
return (
  <div className={`todo-item ${item.done ? 'done' : ''}`}>
    <input type='checkbox'
      onChange={handleOnChange}
      className='todo-item-check'
      checked={item.done ? 'checked' : ''}>
    </input>
    <span className='todo-item-description'>{item.description}</span>
    <button className='todo-item-remove' onClick={onRemoveClicked}>-</button>
  </div>
)
```

2020-05-05 13:19 UTC, HIPPIEKICK commented on code/src/index.css
> + }
indentation

2020-05-05 13:19 UTC, HIPPIEKICK commented on code/src/index.css
> +  }
indentation

2020-05-05 13:19 UTC, HIPPIEKICK commented on code/src/index.css
> +}
indentation

2020-05-05 13:19 UTC, HIPPIEKICK commented on code/src/reducers/todos.js
> +    removeAll: (state, action) => {
⭐

2020-05-07 07:30 UTC, ingrid2019-ism commented
Hi!

I have fixed the indentation and changed the input field to a button tag 
:)

------ Originalmeddelande ------
Från: "Matilda Arvidsson" <notifications@github.com>
Till: "Technigo/project-todos" <project-todos@noreply.github.com>
Kopia: "ingrid2019-ism" <ingrid.hammargren@gmail.com>; "Author" 
<author@noreply.github.com>
Skickat: 2020-05-05 15:19:23
Ämne: Re: [Technigo/project-todos] Project 15, Ingrid H (#57)

>
>@HIPPIEKICK requested changes on this pull request.
>
>Good job Ingrid! It's nice to see that you're adding some extra 
>features like date and clear-button. Please have another look at the 
>code guidelines: 
>https://www.notion.so/technigo/Guidelines-for-how-to-write-good-code-69ffb59eac4e4358a7c5752efb873c4e 
>and make sure you're using semantic HTML as much as possible (I made a 
>comment about an input which is a button). I've also made a few 
>comments about indentation. I will approve this as soon as you fix 
>indentation and change the button to be a button - apart from that - 
>well done!
>
>--------------------------------------------------------------------------------
>In code/src/App.js 
><https://github.com/Technigo/project-todos/pull/57#discussion_r420069210>:
>
> >      <div>
>
>-      Find me in src/app.js!
>
>+      <Home />
>
>      </div>
>
>
>Since you're only returning one component here, you don't need to wrap 
>it in a div.
>
>--------------------------------------------------------------------------------
>In code/src/components/ShowDate.js 
><https://github.com/Technigo/project-todos/pull/57#discussion_r420070050>:
>
> > +    <>
>
>+      <h1>{today}</h1>
>
>+    </>
>
>
>Same here, you shouldn't need the fragment since you're only returning 
>one element.
>
>--------------------------------------------------------------------------------
>In code/src/components/ShowDate.js 
><https://github.com/Technigo/project-todos/pull/57#discussion_r420070203>:
>
> > +  const d = new Date()
>
>+  const today = d.toDateString()
>
>
>Nice with a date!
>
>--------------------------------------------------------------------------------
>In code/src/components/TodoSummery.js 
><https://github.com/Technigo/project-todos/pull/57#discussion_r420071250>:
>
> > @@ -0,0 +1,18 @@
>
>+import React from 'react'
>
>+import { TodoItem } from 'components/TodoItem'
>
>+import { TodoInput } from 'components/TodoInput'
>
>+import { useSelector } from 'react-redux'
>
>+
>
>+export const TodoSummery = () => {
>
>+
>
>+  const list = useSelector(store => store.todos.list)
>
>
>Since you're only using the items-array, it's better to get only that:
>const items = useSelector(store => store.todos.list.items)
>
>--------------------------------------------------------------------------------
>In code/src/components/TodoInput.js 
><https://github.com/Technigo/project-todos/pull/57#discussion_r420072679>:
>
> > +import React from 'react'
>
>+import { useState } from "react"
>
>
>You can import these on the same row, since they have the same source:
>import React, { useState } from 'react'
>
>--------------------------------------------------------------------------------
>In code/src/components/TodoInput.js 
><https://github.com/Technigo/project-todos/pull/57#discussion_r420072992>:
>
> > @@ -0,0 +1,37 @@
>
>+import React from 'react'
>
>+import { useState } from "react"
>
>+import { useDispatch } from 'react-redux'
>
>+import { todos } from 'reducers/todos'
>
>+
>
>+export const TodoInput = () => {
>
>+  const dispatch = useDispatch()
>
>+  const [inputValue, setInputValue] = useState('')
>
>+  const handleOnSubmit = (event) => {
>
>+    event.preventDefault()
>
>+    dispatch(todos.actions.addTodo({
>
>+      description: inputValue,
>
>+      done: false
>
>+    }))
>
>+    setInputValue('')
>
>
>Good that you're clearing the input! Right now you can submit empty 
>todos, so maybe set the input-field to be required, or check if the 
>input is empty before actually dispatching.
>
>--------------------------------------------------------------------------------
>In code/src/components/TodoInput.js 
><https://github.com/Technigo/project-todos/pull/57#discussion_r420074665>:
>
> > +      <input
>
>+        Type='submit'
>
>+        className='todo-input-button'
>
>+        value='+'
>
>+      ></input>
>
>
>Don't forget to use semantic HTML - this is a button so why not call it 
>a button? 😉
>
>--------------------------------------------------------------------------------
>In code/src/components/TodoInput.js 
><https://github.com/Technigo/project-todos/pull/57#discussion_r420075534>:
>
> > +      <input
>
>+        Type='text'
>
>+        placeholder='Add Todo'
>
>+        onChange={event => setInputValue(event.target.value)}
>
>+        value={inputValue}
>
>+        className='todo-input-text'
>
>+      ></input>
>
>
>Since the input-element doesn't have any children you can just make it 
>self closing instead of with opening and closing tags:
>
><input
>
>   type='text'
>
>   placeholder='Add Todo'
>
>   onChange={event => setInputValue(event.target.value)}
>
>   value={inputValue}
>
>   className='todo-input-text'
>
>/>
>
>
>--------------------------------------------------------------------------------
>In code/src/components/RemoveAll.js 
><https://github.com/Technigo/project-todos/pull/57#discussion_r420081572>:
>
> > +    <button className='remove-button'
>
>+      type='button'
>
>+      onClick={() => dispatch(todos.actions.removeAll())}>
>
>+      Clear
>
>+    </button>
>
>
>Nice with a clear-button!
>
>--------------------------------------------------------------------------------
>In code/src/components/TodoList.js 
><https://github.com/Technigo/project-todos/pull/57#discussion_r420082123>:
>
> > +import { TodoInput } from 'components/TodoInput'
>
>+import { TodoSummery } from 'components/TodoSummery'
>
>
>Remove unused code
>
>--------------------------------------------------------------------------------
>In code/src/components/TodoList.js 
><https://github.com/Technigo/project-todos/pull/57#discussion_r420082676>:
>
> > @@ -0,0 +1,22 @@
>
>+import React from 'react'
>
>+import { TodoItem } from 'components/TodoItem'
>
>+import { TodoInput } from 'components/TodoInput'
>
>+import { TodoSummery } from 'components/TodoSummery'
>
>+import { useSelector } from 'react-redux'
>
>+
>
>+export const TodoList = () => {
>
>+
>
>+  const list = useSelector(store => store.todos.list)
>
>
>Same here, you're only using the items-array so get only that instead:
>const items = useSelector(store => store.todos.list.items)
>
>--------------------------------------------------------------------------------
>In code/src/components/TodoItem.js 
><https://github.com/Technigo/project-todos/pull/57#discussion_r420085859>:
>
> > +  return <div className={`todo-item ${item.done ? 'done' : ''}`}>
>
>+    <input type='checkbox'
>
>+      onChange={handleOnChange}
>
>+      className='todo-item-check'
>
>+      checked={item.done ? 'checked' : ''}></input>
>
>+    <span className='todo-item-description'>{item.description}</span>
>
>+    <button className='todo-item-remove' onClick={onRemoveClicked}>-</button>
>
>+  </div >
>
>
>Nice with conditional styling! Try to be consistent with parentheses 
>after return and maybe clean this up a bit (so the <div> gets its own 
>line and the </div> don't have a space):
>
>return (
>
>   <div className={`todo-item ${item.done ? 'done' : ''}`}>
>
>     <input type='checkbox'
>
>       onChange={handleOnChange}
>
>       className='todo-item-check'
>
>       checked={item.done ? 'checked' : ''}>
>
>     </input>
>
>     <span className='todo-item-description'>{item.description}</span>
>
>     <button className='todo-item-remove' onClick={onRemoveClicked}>-</button>
>
>   </div>
>
>)
>
>
>--------------------------------------------------------------------------------
>In code/src/index.css 
><https://github.com/Technigo/project-todos/pull/57#discussion_r420087414>:
>
> > +.header {
>
>+  display: flex;
>
>+  flex-directi [...]

2020-05-07 07:37 UTC, HIPPIEKICK approved these changes

2020-05-07 07:38 UTC, HIPPIEKICK commented
Awesome!

2020-11-09 16:59 UTC, closed without merging