Project TODOS- Elin Leidstedt
Technigo/project-todos pull request #60
Opened 2020-04-24 15:28 UTC by Leidstedt

Link to my deployed project: https://app.netlify.com/sites/affectionate-borg-3fcc3c/overview

My reflections on how this week's project turned out: Better than expected... 

Things I'd like to have clarified or explained in more detail: The "flow" of data... is it possible to visualize it somehow?

2020-05-01 14:16 UTC, JennieDalgren requested changes
Good job with this project!

Regarding your question about seeing the "flow" of data. Try to play around and look in the redux dev tool to see whats going on with the actions and the state. 

Make sure to fix up your indentation, remember that we use 2 space indentation at Technigo. But most importantly - be consistent! Reqruiters or others looking at your code will think it's messy and that will sadly have an impact of the overall evaluation of your code.
When indentation is fixed, I can approve this! 👍 

Keep up the good work!

2020-05-01 14:16 UTC, JennieDalgren commented on code/src/App.js
> +      <Home />
you don't need to wrap the `<Home />` component in divs since it's just one.

2020-05-01 14:16 UTC, JennieDalgren commented on code/src/components/AddTaskForm.js
> +        console.log(inputValue)
remove console log. 
Also, maybe add a check to see if the input is empty or not before adding it. Right now you can save an empty todo

2020-05-01 14:16 UTC, JennieDalgren commented on code/src/components/AddTaskForm.js
> +        <lable>
<label> not <lable>

2020-05-01 14:16 UTC, JennieDalgren commented on code/src/components/AddTaskForm.js
> +    <section className=''>
remove className of not used

2020-05-01 14:16 UTC, JennieDalgren commented on code/src/components/Header.js
> +)
Here you can use an implicit return like this:
```
export const Header = () => (
    <section className='header'>
        <h1>To-do-list</h1>
    </section>  
)
```

Read more about[ explicit vs implicit returns here](https://dev.to/samanthaming/es6-arrow-functions-cheatsheet-1cn)

2020-05-01 14:16 UTC, JennieDalgren commented on code/src/components/ItemList.js
> +    )
Fix indentation!

2020-05-01 14:16 UTC, JennieDalgren commented on code/src/components/ItemList.js
> +       <Task itemIndex={index}></Task>
Don't forget the `key` prop

2020-05-01 14:16 UTC, JennieDalgren commented on code/src/components/ListSummary.js
> +    </section>
indentation!

2020-05-01 14:16 UTC, JennieDalgren commented on code/src/components/Task.js
> +                itemIndex: itemIndex
when key and value is the same `itemIndex: itemIndex` your can write it just once `itemIndex`

2020-05-01 14:16 UTC, JennieDalgren commented on code/src/components/Task.js
> +                itemIndex: itemIndex,
same here as above with key and value

2020-05-01 14:16 UTC, JennieDalgren commented on code/src/components/Task.js
> +            </label>
indentation!

2020-05-01 14:16 UTC, JennieDalgren commented on code/src/pages/Home.js
> +        <ItemList></ItemList>
this can be written as a self closing tag
`<ItemList />`

2020-05-01 14:16 UTC, JennieDalgren commented on code/src/reducers/todolist.js
> +      const { itemIndex, done } =action.payload
space after `=`

2020-05-01 14:16 UTC, JennieDalgren commented on code/src/reducers/todolist.js
> +      const { itemIndex } =action.payload
space after `=`

2020-05-05 14:20 UTC, Leidstedt commented
Hi! Now the page is updated. Do I send a new pull request?

2020-05-05 16:28 UTC, JennieDalgren approved these changes
Perfect! All good 🎉

2020-11-09 17:00 UTC, closed without merging