Todo Today - Week 15 - Andrea
Technigo/project-todos pull request #90
Opened 2020-11-27 13:40 UTC by Andrea-Osmar

Link to my deployed project: https://todos-today.netlify.app/

My reflections on how this week's project turned out: I found redux very hard to understand but looking forward to learning more.

Things I'd like to have clarified or explained in more detail: When all tasks are deleated and I'm entering new tasks they get id: null and after that I can not delete just one task. Would like some help to get the new tasks to get unique id's.

2020-12-02 07:19 UTC, ylvan75 requested changes
Nice work Andrea!

I like that you Todo-app has a clean and clear design. By using + and - for adding and removing stuff makes it user friendly. No need to read anything, that I like.

I guess almost all of us probably have the same structure in the code but that we may have named our components a little differently. This made it easy to compare my code with yours but at the same time difficult to give constructive feedback on the code.

I have found some things that can be improved but in general I think your code looks clean and you have divided it up in smaller components which makes it easy to review it. 
Really good consistence at the top of each files with the importing structure

I have one thing that I'm curious about if your Todo-app still will work if you do the change that I suggest.

--> It's in TaskInput.js

**So before I approve it I would appreciate that you update your code with this (see above) and see if it still works, if yes please update your PR.** 

Besides that, I just say again good job!

2020-12-02 07:19 UTC, ylvan75 commented on code/src/Reducers/todo.js
> +      console.log(action.payload)
Could be removed (I sometimes forget to remove them also)

2020-12-02 07:19 UTC, ylvan75 commented on code/src/Reducers/todo.js
> +      store.items.push(newItem)
Another solution could be to use spread syntax with an array to update array items. Like this: 

`store.items = [...store.items, newItem];`

2020-12-02 07:19 UTC, ylvan75 commented on code/src/Components/Header.js
> +        <TaskSummary></TaskSummary>
This is enough, since it's a component you adding here 

```suggestion
        <TaskSummary />
```

2020-12-02 07:19 UTC, ylvan75 commented on code/src/Components/TaskSummary.js
> +  const completedTasks = items.filter((item) => item.isComplete).length
I like that you already here decided to store the value of how many in numbers the completed tasks are.

What I mean is that you did `.length`

2020-12-02 07:19 UTC, ylvan75 commented on code/src/Components/TaskInput.js
> +      <button className="task-add-button" type="submit" onClick={handleSubmit}>
This shouldn't be need 

`onClick={handleSubmit}`

```suggestion
      <button className="task-add-button" type="submit">
```

since you on line 24 say the to the form `onSubmit={handleSubmit}`

Try to remove and see if it still works!

2020-12-02 07:19 UTC, ylvan75 commented on code/src/Components/TaskItem.js
> +    dispatch(todo.actions.removeItem({ id: item.id }))
```suggestion
    dispatch(todo.actions.removeItem({ item.id }))
```

as you did on line 11.

Not 100% if I think right here since you passing in an argument in this case. I'm curious if it will work with my suggestion.

2020-12-02 07:19 UTC, ylvan75 commented on code/src/Components/TaskItem.js
> +            checked={checked}
```suggestion
            checked={item.isCompleted}
```

so then you can remove line 8, no need to having a local state here.

2020-12-02 07:19 UTC, ylvan75 commented on code/src/index.css
> +}
I like this hovering effect on you Remove all /Are you already done? button :-)

2020-12-02 07:19 UTC, ylvan75 commented on code/src/index.css
> +@import url('https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap');
I will just highlight what Johanna pointed out for me in one of my projects.

Good practice to add box-sizing: border box at the top. 

This is what she suggested to add to the the top of the css-file. Must be honest and say that I don't fully understand the after and before thing.

```suggestion
*,
*::after,
*::before {
  box-sizing: border-box;
}

@import url('https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap');
```

2020-12-02 07:19 UTC, ylvan75 commented on code/src/index.css
> +  box-sizing: border-box;
Aha now I see that you have used it, still perhaps a good idea to have it at the top so it's used for the whole css-file.

2020-12-02 07:19 UTC, ylvan75 commented on code/src/index.css
> +  word-break: break-word;
Nice!

Something I missed in my project.

2020-12-02 07:19 UTC, ylvan75 commented on code/src/index.css
> +/* CHECKBOX */
Great job with your checkbox & checkmark. I'm impressed with your CSS skills :-)

2020-12-05 13:04 UTC, Andrea-Osmar commented on code/src/Reducers/todo.js
> +      store.items.push(newItem)
Thank you :)

2020-12-05 13:04 UTC, Andrea-Osmar commented on code/src/Components/TaskInput.js
> +      <button className="task-add-button" type="submit" onClick={handleSubmit}>
I tried it out and it works :D Thank you!!

2020-12-05 13:08 UTC, Andrea-Osmar commented on code/src/Components/TaskItem.js
> +    dispatch(todo.actions.removeItem({ id: item.id }))
It gets angry when i try this :(

2020-12-05 13:09 UTC, Andrea-Osmar commented on code/src/index.css
> +}
Thank you :D

2020-12-05 16:07 UTC, ylvan75 approved these changes
The updates looks good!

2020-12-10 16:09 UTC, HIPPIEKICK commented on code/src/App.js
> +    <ClearButton />
Indentation ;)

2020-12-10 16:09 UTC, HIPPIEKICK commented on code/src/Components/Header.js
> +import moment from "moment"
⭐

2020-12-10 16:10 UTC, HIPPIEKICK commented on code/src/Components/TaskItem.js
> +    dispatch(todo.actions.removeItem({ id: item.id }))
You can either have it as you did or update the reducer so that it understands that the payload = id.

2020-12-10 16:19 UTC, HIPPIEKICK commented on code/src/Components/TaskInput.js
> +        <input
Prevent the user from submitting an empty input

2020-12-10 16:20 UTC, HIPPIEKICK commented on code/src/Library/ClearButton.js
> +      <span className="clear-button-before">Remove All</span>
`letter-spacing: 1px;` 😎

2020-12-10 16:21 UTC, HIPPIEKICK commented on code/src/Reducers/todo.js
> +      { id: 1, text: "Eat", isComplete: true },
Nice boolean name 👍

2021-03-09 13:11 UTC, closed without merging