Handing in the project for week 15
Technigo/project-todos pull request #92
Opened 2020-11-27 15:46 UTC by HenrikeW

Link to my deployed project: https://henrikes-todo.netlify.app/

My reflections on how this week's project turned out: I think this project was really fun! It was the right level of challenge where I had to think and try different approaches most of the times but never got really stuck. I did the requirements for the red level but would have liked to implement more features if there had been more time. I might go back to this project later on to implement those (most of all a local storage) to be able to actually use the app.

Things I'd like to have clarified or explained in more detail: I used styled components but still struggle with them and would like to learn more about cases where they actually have advantages compared to plain css, like e.g. when passing props. In nearly all components I felt that I could have written the same amount of code using classnames instead but I feel that it's probably because I don't see the whole potential of styled components yet.

2020-12-02 17:26 UTC, MindstormingAB requested changes
Really great job Henrike!
You demonstrated a good understanding of Redux state and reducers by nailing the blue and red levels requirements. Your app and your code are clean and well designed.
I found several solutions that I'll try to remember for my own projects 🙏 
Before this project can be approved, some changes are required:
- your bottom bar is hiding the last todo when there are more than 3 todos, can you improve that?
- you're using a styled component built on a `li` to wrap your input form which negatively impacts your html semantic.
- your images are missing `alt`
- you're missing some semicolons and the indentation needs to be revised here and there
- remove console.log
Keep up the good work!

2020-12-02 17:26 UTC, MindstormingAB commented on README.md
> +You can see the site up and running here: https://henrikes-todo.netlify.app/
Wow! 🤩

2020-12-02 17:26 UTC, MindstormingAB commented on code/public/index.html
> +    <link rel="preconnect" href="https://fonts.gstatic.com">
What is preconnect? ⁉

2020-12-02 17:26 UTC, MindstormingAB commented on code/src/components/AddTask.js
> +      <AddForm onSubmit={onAddTask}>
I understand that you want to reuse your styled components in different places to keep the code short and consistent but, in this case, you're ending up with a list item outside the list. Maybe you could use more styling in `<AddForm>` and use it as container instead of `<ListItem>`.

2020-12-02 17:26 UTC, MindstormingAB commented on code/src/components/AddTask.js
> +        <img src={require('assets/plus.svg')} alt='' style={{width: '20px'}}/>
Mind the indentation and put some useful description in `alt` 😏
What about creating styled component for your image so you can avoid the inline style?

2020-12-02 17:26 UTC, MindstormingAB commented on code/src/components/AddTask.js
> +          type='submit'
If you use an input as Button, you should add `role= 'button'` for accessibility purpose.

2020-12-02 17:26 UTC, MindstormingAB commented on code/src/components/AddTask.js
> +  }
Is it a missing semicolon I'm spotting? 🔍

2020-12-02 17:26 UTC, MindstormingAB commented on code/src/components/AddTask.js
> +}
More missing semicolons 🙄

2020-12-02 17:26 UTC, MindstormingAB commented on code/src/components/Bottom.js
> +    })
Interesting

2020-12-02 17:26 UTC, MindstormingAB commented on code/src/components/Bottom.js
> +        disabled={allTasks.length === 0 ? true : false}
Well done!

2020-12-02 17:26 UTC, MindstormingAB commented on code/src/components/DoneButton.js
> +        <img src={require('assets/check.svg')} alt='' style={{width: '20px'}}/>
`alt`?

2020-12-02 17:26 UTC, MindstormingAB commented on code/src/components/Summary.js
> +}
Great code but check if you are missing any semicolon

2020-12-02 17:26 UTC, MindstormingAB commented on code/src/components/TaskList.js
> +        <img src={require('assets/Party.svg')} alt='' style={{width: '45vh'}}/>
`alt`?

2020-12-02 17:26 UTC, MindstormingAB commented on code/src/reducers/todos.js
> +        id: store.tasks.length === 0 ? 0 : Math.max(...store.tasks.map(item => item.id)) + 1,
Good job adding this logic to the Math.max id solution

2020-12-02 17:26 UTC, MindstormingAB commented on code/src/reducers/todos.js
> +      currentItem.done === true ? currentItem.done = false : currentItem.done = true;
That works but you could have used 
```suggestion
      currentItem.done === !currentItem.done;
```
to toggle the done status

2020-12-02 17:26 UTC, MindstormingAB commented on code/src/reducers/todos.js
> +      console.log(doneList)
console.log is great for testing purposes but don't forget to remove it when you're done 🧐

2020-12-02 17:26 UTC, MindstormingAB commented on code/src/reducers/todos.js
> +    },
Another (shorter) way to do that:
```suggestion
        markAllDone: (store, action) => {
            store.tasks = store.tasks.map((task) => {
                    task.done = true
                    return task
                })
        },
```

2020-12-02 17:26 UTC, MindstormingAB commented on code/src/reducers/todos.js
> +      store.tasks = emptyList;
Or maybe
```suggestion
      store.tasks = [];
```
😉

2020-12-02 17:26 UTC, MindstormingAB commented on code/src/components/DoneButton.js
> +      )
So clever! 💯

2020-12-02 17:26 UTC, MindstormingAB commented on code/src/styles/bottomStyles.js
> +`
Unfortunately, when you have more than 3 todos, this container hides the last todo.

2020-12-02 17:26 UTC, MindstormingAB commented on code/src/styles/bottomStyles.js
> +}
Review indentation 👓

2020-12-15 16:38 UTC, HIPPIEKICK commented on code/src/components/Bottom.js
> +        disabled={allTasks.length === 0 || notDoneTasks.length === 0 ? true : false}
Nice!

2020-12-15 16:40 UTC, HIPPIEKICK commented on code/src/components/TaskListItem.js
> +        <Timestamp>{moment(task.created).fromNow()}</Timestamp>
Nice!

2020-12-15 16:44 UTC, HIPPIEKICK commented
Great job Henrike - a lot of cool functionality going on here! 💪   Take a look at Sandrine's comments, especially:
- your bottom bar is hiding the last todo when there are more than 3 todos, can you improve that?
- you're missing some semicolons and the indentation needs to be revised here and there
- remove console.log

and you will be approved :)

2021-02-16 16:22 UTC, HenrikeW commented on code/src/components/AddTask.js
> +      <AddForm onSubmit={onAddTask}>
Thanks for the tip! Did that.

2021-02-16 17:11 UTC, HenrikeW commented on code/src/reducers/todos.js
> +    },
Thanks for the suggestion. I thought, the longer way was a better way of doing it because of immutability. But maybe I was wrong?

2021-02-16 17:11 UTC, HenrikeW commented on code/src/reducers/todos.js
> +      store.tasks = emptyList;
Same here. Isn't it better to first create another variable because of immutability reasons?

2021-02-17 13:14 UTC, HenrikeW commented on code/src/styles/bottomStyles.js
> +`
Solved!

2021-02-17 13:16 UTC, HenrikeW commented
Finally, I fixed the footer issue. It's not hiding any content any more. Also, I removed console.logs, added missing semicolons and cleaned up the indentation. As far as I see it, everything should be done now.

2021-03-09 13:15 UTC, closed without merging